${request.setHeader('TradeId', xml["/FXFWD/TradeId/text()"])}
<@compress single_line=true>
<#--  general -->
${xml["/FXFWD/TradeId"]},
${xml["/FXFWD/TradeType"]},
${xml["/FXFWD/Env/ENV/Book"]},
${xml["/FXFWD/Env/ENV/Desk"]},
<#if xml["/FXFWD/Env/ENV/Folder"][0]??>${xml["/FXFWD/Env/ENV/Folder"]}</#if>,
${xml["/FXFWD/Env/ENV/Cust"]},
${xml["/FXFWD/Env/ENV/TradeDate"]},
<#if xml["/FXFWD/Back/BACK/ExtSystem"][0]??>${xml["/FXFWD/Back/BACK/ExtSystem"]}</#if>,
${xml["/FXFWD/Forex/FOREX/SoldCcy"]},
<#--  FXFWD specific -->
${xml["/FXFWD/Forex/FOREX/FxType"]},
${xml["/FXFWD/Forex/FOREX/PorS"]},
${xml["/FXFWD/Forex/FOREX/Valdate"]},
${xml["/FXFWD/Forex/FOREX/BoughtCcy"]},
<#if xml["/FXFWD/Forex/FOREX/BoughtAmt"][0]??>${xml["/FXFWD/Forex/FOREX/BoughtAmt"]}</#if>,
${xml["/FXFWD/Forex/FOREX/SoldCcy"]},
<#if xml["/FXFWD/Forex/FOREX/SoldAmt"][0]??>${xml["/FXFWD/Forex/FOREX/SoldAmt"]}</#if>,
${xml["/FXFWD/Forex/FOREX/XRate"]},
${xml["/FXFWD/Forex/FOREX/Terms"]},
${xml["/FXFWD/Forex/FOREX/SpotRate"]},
${xml["/FXFWD/Forex/FOREX/FwdPoints"]},
${xml["/FXFWD/Forex/FOREX/SpotDate"]},
${xml["/FXFWD/Forex/FOREX/BoughtDate"]},
${xml["/FXFWD/Forex/FOREX/SoldDate"]},
<#if xml["/FXFWD/Forex/FOREX/BoughtRate"][0]??>${xml["/FXFWD/Forex/FOREX/BoughtRate"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/SoldRate"][0]??>${xml["/FXFWD/Forex/FOREX/SoldRate"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/SplitRate"][0]??>${xml["/FXFWD/Forex/FOREX/SplitRate"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/SplitPoints"][0]??>${xml["/FXFWD/Forex/FOREX/SplitPoints"]}</#if>,
${xml["/FXFWD/Forex/FOREX/Style"]},
<#if xml["/FXFWD/Forex/FOREX/dmOwnerTable"][0]??>${xml["/FXFWD/Forex/FOREX/dmOwnerTable"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/Audit_Version"][0]??>${xml["/FXFWD/Forex/FOREX/Audit_Version"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/ShortBoughtRate"][0]??>${xml["/FXFWD/Forex/FOREX/ShortBoughtRate"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/ShortSoldRate"][0]??>${xml["/FXFWD/Forex/FOREX/ShortSoldRate"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/ShortFwdPoints"][0]??>${xml["/FXFWD/Forex/FOREX/ShortFwdPoints"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/ShortXRate"][0]??>${xml["/FXFWD/Forex/FOREX/ShortXRate"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/SplitXRate"][0]??>${xml["/FXFWD/Forex/FOREX/SplitXRate"]}</#if>,
${xml["/FXFWD/Forex/FOREX/BaseRate"]},
<#if xml["/FXFWD/Forex/FOREX/BaseAmount"][0]??>${xml["/FXFWD/Forex/FOREX/BaseAmount"]}</#if>,
${xml["/FXFWD/Forex/FOREX/UserSelectedFlag"]},
<#if xml["/FXFWD/Forex/FOREX/CorporateCcy"][0]??>${xml["/FXFWD/Forex/FOREX/CorporateCcy"]}</#if>,
${xml["/FXFWD/Forex/FOREX/InterbankRate"]},
${xml["/FXFWD/Forex/FOREX/InterbankFwdPts"]},
<#if xml["/FXFWD/Forex/FOREX/ClientSpread"][0]??>${xml["/FXFWD/Forex/FOREX/ClientSpread"]}</#if>,
${xml["/FXFWD/Forex/FOREX/MarginType"]},
${xml["/FXFWD/Forex/FOREX/InterbankSpotRate"]},
<#if xml["/FXFWD/Forex/FOREX/ClientSpotSpread"][0]??>${xml["/FXFWD/Forex/FOREX/ClientSpotSpread"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/ClientFwdPtsSpread"][0]??>${xml["/FXFWD/Forex/FOREX/ClientFwdPtsSpread"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/DevaluationRate"][0]??>${xml["/FXFWD/Forex/FOREX/DevaluationRate"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/ShortDevaluationRate"][0]??>${xml["/FXFWD/Forex/FOREX/ShortDevaluationRate"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/SVDCcy1Interest"][0]??>${xml["/FXFWD/Forex/FOREX/SVDCcy1Interest"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/SVDCcy2Interest"][0]??>${xml["/FXFWD/Forex/FOREX/SVDCcy2Interest"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/SVDFwdPoints"][0]??>${xml["/FXFWD/Forex/FOREX/SVDFwdPoints"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/SVDShortCcy1Interest"][0]??>${xml["/FXFWD/Forex/FOREX/SVDShortCcy1Interest"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/SVDShortCcy2Interest"][0]??>${xml["/FXFWD/Forex/FOREX/SVDShortCcy2Interest"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/SVDShortPoints"][0]??>${xml["/FXFWD/Forex/FOREX/SVDShortPoints"]}</#if>,
<#if xml["/FXFWD/Forex/FOREX/SVDTrueSpotRate"][0]??>${xml["/FXFWD/Forex/FOREX/SVDTrueSpotRate"]}</#if>
</@compress>